# Generated by Django 4.2.5 on 2023-09-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_customuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("undergraduate", "Undergraduate"),
                    ("postgraduate", "Postgraduate"),
                ],
                default="undergraduate",
                max_length=20,
            ),
        ),
    ]
