# Generated by Django 4.2.5 on 2023-09-09 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UpdateTable",
            new_name="KnowledgeBase",
        ),
    ]
