# Generated by Django 4.2.5 on 2023-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_customuser_about_you"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
