# Generated by Django 4.2.5 on 2023-09-06 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback_details", models.TextField()),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("Accuracy", "Accuracy"),
                            ("Performance", "Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UpdateTable",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("update_information", models.TextField()),
                (
                    "update_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.feedback",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "chat_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("conversation_title", models.CharField(max_length=255)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
